FROM node:18.1.0-alpine3.14

WORKDIR /marketingar

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SABA_API
ARG NEXT_PUBLIC_SABA_AUTH_KEY

ENV NEXT_PUBLIC_API_URL $NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SABA_API $NEXT_PUBLIC_SABA_API
ENV NEXT_PUBLIC_SABA_AUTH_KEY $NEXT_PUBLIC_SABA_AUTH_KEY

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]